/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSmeAppsRouteImport } from './routes/_chat.sme-apps'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatSalesSkillsRouteImport } from './routes/_chat.sales-skills'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSmeAppsRoute = ChatSmeAppsRouteImport.update({
  id: '/sme-apps',
  path: '/sme-apps',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSalesSkillsRoute = ChatSalesSkillsRouteImport.update({
  id: '/sales-skills',
  path: '/sales-skills',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/sales-skills': typeof ChatSalesSkillsRoute
  '/settings': typeof ChatSettingsRoute
  '/sme-apps': typeof ChatSmeAppsRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/sales-skills': typeof ChatSalesSkillsRoute
  '/settings': typeof ChatSettingsRoute
  '/sme-apps': typeof ChatSmeAppsRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/sales-skills': typeof ChatSalesSkillsRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/sme-apps': typeof ChatSmeAppsRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$threadId' | '/sales-skills' | '/settings' | '/sme-apps'
  fileRoutesByTo: FileRoutesByTo
  to: '/$threadId' | '/sales-skills' | '/settings' | '/sme-apps' | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/sales-skills'
    | '/_chat/settings'
    | '/_chat/sme-apps'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sme-apps': {
      id: '/_chat/sme-apps'
      path: '/sme-apps'
      fullPath: '/sme-apps'
      preLoaderRoute: typeof ChatSmeAppsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sales-skills': {
      id: '/_chat/sales-skills'
      path: '/sales-skills'
      fullPath: '/sales-skills'
      preLoaderRoute: typeof ChatSalesSkillsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatSalesSkillsRoute: typeof ChatSalesSkillsRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatSmeAppsRoute: typeof ChatSmeAppsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSalesSkillsRoute: ChatSalesSkillsRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatSmeAppsRoute: ChatSmeAppsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
